# Generated by Django 5.2.3 on 2025-07-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'default_related_name': 'likes', 'ordering': ('created_at',), 'verbose_name': 'Мнение', 'verbose_name_plural': 'мнения'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'default_related_name': 'quotes', 'ordering': ('weight', 'views', 'created_at'), 'verbose_name': 'Цитата', 'verbose_name_plural': 'цитаты'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Источник', 'verbose_name_plural': 'источники'},
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип произведения'),
        ),
    ]
