# Generated by Django 5.2.3 on 2025-07-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_alter_opinion_quote_alter_opinion_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип произведения',
                'verbose_name_plural': 'типы произведений',
            },
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.IntegerField(null=True),
        ),
    ]
