# Generated by Django 5.2.3 on 2025-07-08 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_worktype_alter_source_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='quote.worktype'),
        ),
    ]
