# Generated by Django 5.2.3 on 2025-07-16 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def create_weights(apps, schema_editor):
    Weight = apps.get_model('quote', 'Weight')  # замените 'yourapp'
    Weight.objects.bulk_create([
        Weight(value=i, count=0) for i in range(1, 101)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_add_initial_worktypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(db_index=True, unique=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Вес')),
                ('count', models.PositiveIntegerField(verbose_name='Количество записей')),
            ],
        ),
        migrations.RunPython(create_weights),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quote.weight', verbose_name='Вес цитаты'),
        ),
    ]
